<?php
/**
 * @file
 * Code for the Views Job feature.
 */

include_once 'views_job.features.inc';

/**
 * Implements hook_views_post_execute().
 */
function views_job_views_post_execute(&$view) {
  if ($view->name == 'job') {
    foreach($view->result as $result) {
      if (isset($result->field_field_job_start_date)) {
        $start_date = $result->field_field_job_start_date[0]['rendered']['#markup'];
        $date       = new DateTime($start_date);
        $timestamp  = $date->getTimestamp();
        $formatted  = format_date($timestamp, 'update_date');

        $result->field_field_job_start_date[0]['rendered']['#markup'] = $formatted;
        $result->field_field_job_start_date[0]['raw']['value']        = $formatted;
        $result->field_field_job_start_date[0]['raw']['safe_value']   = $formatted;
      }
    }
  }
}
