<?php
/**
 * @file
 * Code for the Views Administration Content referenced by feature.
 */

include_once 'views_administration_content_referenced_by.features.inc';

/**
 * Implements hook_admin_paths().
 */
function views_administration_content_referenced_by_admin_paths() {
  return array(
    'node/*/faq-referenced-by' => TRUE,
    'node/*/factbox-referenced-by' => TRUE,
    'node/*/selfservice-referenced-by' => TRUE,
    'node/*/bannerlink-referenced-by' => TRUE,
    'node/*/phonebook-referenced-by' => TRUE,
    'node/*/borgerdk-referenced-by' => TRUE,
  );
}
