version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.1-2.3.5
    container_name: favrskov_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: favrskov
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - ~/mariadb-init/favrskov:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
      - ~/docker-runtime/favrskov:/var/lib/mysql # I want to manage volumes manually.

  php:
    image: 185836940016.dkr.ecr.eu-west-1.amazonaws.com/php_5.6_main_drupal:latest
    container_name: favrskov_php
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_FPM_CLEAR_ENV: "no"
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: favrskov
      DB_DRIVER: mysql
    volumes:
      # Options for macOS users (https://docker4drupal.readthedocs.io/en/latest/macos)
      - ./:/var/www/html # Docker-sync

  apache:
    image: wodby/php-apache:2.4-2.0.0
    container_name: favrskov_apache
    depends_on:
      - php
    environment:
      APACHE_LOG_LEVEL: debug
      APACHE_BACKEND_HOST: php
      APACHE_SERVER_ROOT: /var/www/html
    volumes:
      # Options for macOS users (https://docker4drupal.readthedocs.io/en/latest/macos)
      - ./:/var/www/html # Docker-sync
    labels:
      - 'traefik.backend=apache'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:favrskov.loc'

  varnish:
    image: wodby/drupal-varnish:4.1-2.2.0
    container_name: favrskov_varnish
    depends_on:
      - apache
    environment:
      VARNISH_SECRET: secret
      VARNISH_BACKEND_HOST: apache
      VARNISH_BACKEND_PORT: 80
    labels:
      - 'traefik.backend=varnish'
      - 'traefik.port=6081'
      - 'traefik.frontend.rule=Host:varnish.drupal.docker.localhost'

  solr:
    image: wodby/drupal-solr:7-5.4-2.2.0
    container_name: favrskov_solr
    environment:
      SOLR_HEAP: 1024m
    labels:
      - 'traefik.backend=solr'
      - 'traefik.port=8983'
      - 'traefik.frontend.rule=Host:solr.drupal.docker.localhost'

  mailhog:
    image: mailhog/mailhog
    container_name: favrskov_mailhog
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.drupal.docker.localhost'

  memcached:
    image: wodby/memcached:1.4-2.0.0
    container_name: favrskov_memcached

  traefik:
    image: traefik
    container_name: favrskov_traefik
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '8000:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
