<?php

/**
 * @file
 *   Feeds directory fetcher module, fetches files from a directory.
 */

/**
 * Implementation of hook_feeds_plugins().
 */
function feeds_fetcher_directory_feeds_plugins() {
  $info = array();
  $info['feeds_fetcher_directory_fetcher'] = array(
    'name' => 'Feeds Fetcher Directory',
    'description' => 'Fetches feeds files from a directory.',
    'handler' => array(
      'parent' => 'FeedsFileFetcher', // A plugin needs to derive either directly or indirectly from FeedsFetcher, FeedsParser or FeedsProcessor.
      'class' => 'feeds_fetcher_directory_fetcher',
      'file' => 'feeds_fetcher_directory_fetcher.inc',
      'path' => drupal_get_path('module', 'feeds_fetcher_directory'),
    ),
  );
  return $info;
}

function feeds_fetcher_directory_ctools_plugin_api($owner, $api) {
  if ($owner == 'feeds' && $api == 'plugins') {
    return array('version' => 1);
  }
}

