<?php
/**
 * @file
 * Code for the Content Type Newsletter feature.
 */

include_once 'content_type_newsletter.features.inc';

function content_type_newsletter_form_newsletter_node_form_alter(&$form, &$form_state, $form_id) {
  if (empty($form['field_mailchimp_template_id']['und'][0]['value']['#default_value'])) {
    $form['field_mailchimp_template_id']['und'][0]['value']['#default_value'] = variable_get('mailchimp_template_id', '');
  }
}