<?php
/**
 * @file
 * Code for the Panel Article page feature.
 */

include_once 'panel_article_page.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function panel_article_page_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && !empty($plugin_type)) {
    return "plugins/{$plugin_type}";
  }
}

/**
 * Return our custom formats.
 *
 * @return
 * info about custom formats
 */
function panel_article_page_date_formats_get_names() {
  static $names = array('update_date' => 'd.m.Y');
  return $names;
}

/**
 * Implements hook_date_formats().
 */
function panel_article_page_date_formats() {
  $formats = array();
  $names = panel_article_page_date_formats_get_names();

  foreach ($names as $key => $value) {
    $formats[] = array(
      'type' => $key,
      'format' => $value,
      'locales' => array(),
    );
  }

  return $formats;
}

/**
 * Implements hook_date_format_types().
 */
function panel_article_page_date_format_types() {
  $types = array();
  $names = panel_article_page_date_formats_get_names();

  foreach ($names as $key => $value) {
    $types[$key] = t($key);
  }

  return $types;
}

/**
 * Implements hook_flush_caches().
 */
function panel_article_page_flush_caches() {
  $names = panel_article_page_date_formats_get_names();
  foreach ($names as $key => $value) {
    $formats = system_get_date_formats($key);
    variable_set('date_format_' . $key, $value);

    foreach ($formats as $format) {
      if (!empty($format['dfid'])) {
        system_date_format_delete($format['dfid']);
      }
    }
  }
}