<?php
/**
 * @file
 * Code for the Content Type Article feature.
 *
 * Article is a content type with comments feature. Contains a lot of node and taxonomy references
 * and a publication field collection.
 */

include_once 'content_type_article.features.inc';


/**
 * Implements hook_field_collection_is_empty_alter().
 *
 * We have an 'Open in new window' option in the publication field collection which is selected by default.
 * So we must inform 'field collection' module that field collection instance with all empty fields except that option
 * is an empty field collection instance to disable validation errors.
 */
function content_type_article_field_collection_is_empty_alter(&$is_empty, $item) {
  if ($item->field_name == 'field_publications') {
    $instances = field_info_instances('field_collection_item', $item->field_name);
    $is_empty = TRUE;
    foreach ($instances as $instance) {
      $field_name = $instance['field_name'];
      if ($field_name != 'field_open_in_new_window') {
        $field = field_info_field($field_name);
        // Determine the list of languages to iterate on.
        $languages = field_available_languages('field_collection_item', $field);

        foreach ($languages as $langcode) {
          if (!empty($item->{$field_name}[$langcode])) {
            // If at least one collection-field is not empty; the
            // field collection item is not empty.
            foreach ($item->{$field_name}[$langcode] as $field_item) {
              if (!module_invoke($field['module'], 'field_is_empty', $field_item, $field)) {
                $is_empty = FALSE;
              }
            }
          }
        }
      }
    }
  }
}

/**
 * Implements hook_preprocess field().
 *
 * Changes 'publications' field collection output.
 */
function content_type_article_preprocess_field(&$variables, $hook) {
  if ($variables['element']['#field_name'] == 'field_publications') {
    foreach ($variables['items'] as &$item) {
      foreach ($item['entity']['field_collection_item'] as &$field_collection_item) {
        $item['link'] = '';

        if (!empty($field_collection_item['field_pdf_file'])) {
          $file = $field_collection_item['field_pdf_file']['#object']->field_pdf_file['und'][0];
          $new_window = $field_collection_item['field_pdf_file']['#object']->field_open_in_new_window['und'][0]['value'] == 1;
          $field_collection_item['field_pdf_file'] = [
            '#theme' => 'link',
            '#text' => $file['field_link_title']['und'][0]['safe_value'] != '' ? $file['field_link_title']['und'][0]['safe_value'] : $file['filename'],
            '#path' => file_create_url($file['uri']),
            '#options' => ['attributes' => ['target' => ($new_window ? '_blank' : '_self')]],
            '#prefix' => '<span class="file">',
            '#suffix' => '</span>',
          ];
        }
        else {
          if (!empty($field_collection_item['field_link'])) {
            $item['link'] = $field_collection_item['field_link'];
          }
        }
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function content_type_article_form_article_node_form_alter(&$form, &$form_state, $form_id) {
  $form['field_update_category']['#states'] = array(
    'required' => array(
      '#edit-field-send-update-und' => array('checked' => TRUE),
    ),
  );
}

/**
 * Implements hook_permission().
 */
function content_type_article_permission() {
  return array(
    'allow publish newly created articles' => array(
      'title' => t("Allow users to publish an Article."),
      'description' => t("This permission is related to those articles that haven't been published before."),
    ),
  );
}

/**
 * Implements hook_workbench_moderation_states_next_alter().
 */
function content_type_article_workbench_moderation_states_next_alter(&$states, $current_state, $context) {
  $is_article = $context['node']->type == 'article';
  $published = workbench_moderation_state_published();
  // Disable publishing ability during articles creation.
  if ($is_article && empty($context['node']->nid) && !user_access('allow publish newly created articles')) {
    unset($states[$published]);
  }
  // Disable publishing ability during articles editing before Oficcer has been published it.
  elseif ($is_article && !empty($context['node']->nid) && !user_access('allow publish newly created articles')) {
    $result = db_select('workbench_moderation_node_history', 'h')
      ->fields('h')
      ->condition('nid', $context['node']->nid)
      ->condition('state', $published)
      ->execute();

    if ($result->rowCount() == 0) {
      unset($states[$published]);
    }
  }
}
