<?php
/**
 * @file
 * Code for the Views Locations feature.
 */

include_once 'views_locations.features.inc';

/**
 * Implements hook_panels_ipe_pane_links_alter().
 */
function views_locations_panels_ipe_pane_links_alter(&$links, $pane, $display) {
  if ($pane['pane']->subtype == 'locations-locations_block_pane') {
    $links['change_header'] = array(
      'title' => t('Edit text'),
      'href' => 'views_ui_basic/locations/locations_block_pane/header',
      'attributes' => array(
        'target' => '_blank',
      ),
    );
  }
}

/**
 * Implements hook_admin_paths().
 */
function views_locations_admin_paths() {
  $paths = array(
    'views_ui_basic/*' => TRUE,
  );
  return $paths;
}
