---
# This script contains commands to fill out Drupal settings after installation.
- name: Getting name for settings (WINDOWS)
  set_fact: platform_settings_file={{ tmp_folder }}/reinstall_settings.php
  when: is_windows

- name: Getting name for settings (UNIX)
  set_fact: platform_settings_file={{ settings_file_path }}
  when: is_windows == false

- name: Remove settings.php
  file: name={{ platform_settings_file }} state=absent
  sudo: yes

- name: Creating settings.php
  sudo: yes
  shell: "cp {{ settings_default_file_path }} {{ platform_settings_file }}"

- name: Adding build suffix to base url
  sudo: yes
  lineinfile: dest='{{ platform_settings_file }}' line='$base_url = rtrim($base_url, \"/\") . \"/{{ build_suffix }}\";'

- name: Removing possible slash at the end of base url
  sudo: yes
  lineinfile: dest='{{ platform_settings_file }}' line='$base_url = rtrim($base_url, \"/\");'

- name: Setting up $base_path
  sudo: yes
  lineinfile: dest='{{ platform_settings_file }}' line='$base_path = \"/{{ build_suffix }}/\";'

- name: Checking $base_path for double slash
  sudo: yes
  lineinfile: dest='{{ platform_settings_file }}' line='$base_path = str_replace(\"%//%\", \"/\", $base_path);'

- name: Adding Memcache server to configuration file
  sudo: yes
  lineinfile: dest='{{ platform_settings_file }}' line='$conf["memcache_servers"] = array("{{ memcache_server }}" => "default");'

- name: Adding database variable to settings.php
  sudo: yes
  lineinfile: dest='{{ platform_settings_file }}' line='$databases = array(\"default\" => array (\"default\" => array (\"database\" => \"{{ mysql_db }}\", \"username\" => \"{{ mysql_user }}\", \"password\" => \"{{ mysql_pass }}\", \"host\" => \"{{ mysql_host }}\", \"port\" => \"\", \"driver\" => \"mysql\", \"prefix\" => \"\", ), ), );'

- name: Add general pre-settings to settings.php
  lineinfile: dest='{{ platform_settings_file }}' line='{{ item.name }} = \"{{ item.value }}\";'
  when: item.status == true
  with_items: global_env.pre_settings

- name: Add environment specific pre-settings
  lineinfile: dest='{{ platform_settings_file }}' line='{{ item.name }} = \"{{ item.value }}\";'
  when: item.status == true
  with_items: env.pre_settings

- name: Adding domain configuration file to settings.php
  sudo: yes
  lineinfile: dest='{{ platform_settings_file }}' line='include_once DRUPAL_ROOT . "/profiles/favrskov/modules/contrib/domain/settings.inc";'

- name: Copy settings back (WINDOWS)
  shell: cp {{ platform_settings_file }} {{ settings_file_path }}
  when: is_windows
