<?php
/**
 * @file
 * Code for the View Subject subpages feature.
 */

include_once 'view_subject_subpages.features.inc';

/**
 * Implements hook_views_default_views_alter().
 *
 * Removing default ckeditor view view. We do not need it as we have AWESOME media browser plus.
 */
function view_subject_subpages_views_default_views_alter(&$views) {
  if (isset($views['ckeditor_node_embed'])) {
    unset($views['ckeditor_node_embed']);
  }
}

/**
 * Implements hook_custom_theme().
 */
function view_subject_subpages_custom_theme() {
  if (arg(0) == 'ckeditor-node-embed' && !arg(1)) {
    return variable_get('admin_theme');
  }
}

/**
 * Implements hook_theme_registry_alter()
 * This is where we add our default template for the fckeditor view page template.
 */
function view_subject_subpages_theme_registry_alter(&$theme_registry) {

  //Add 'html--custom-ckeditor-node-embed.tpl.php' template file
  $theme_registry['html__ckeditor_node_embed'] = Array();
  $theme_registry['html__ckeditor_node_embed']['template'] = 'html--custom-ckeditor-node-embed';
  $theme_registry['html__ckeditor_node_embed']['path'] = drupal_get_path('module', 'view_subject_subpages') . "/theme";
  $theme_registry['html__ckeditor_node_embed']['render element'] = 'page';
  $theme_registry['html__ckeditor_node_embed']['base hook'] = 'html';
  $theme_registry['html__ckeditor_node_embed']['type'] = 'theme_engine';
  $theme_registry['html__ckeditor_node_embed']['theme path'] = path_to_theme();
  $theme_registry['html__ckeditor_node_embed']['preprocess functions'] = Array();
  $theme_registry['html__ckeditor_node_embed']['process functions'] = Array();

  //Add 'page--custom-ckeditor-node-embed.tpl.php' template file
  $theme_registry['page__ckeditor_node_embed'] = Array();
  $theme_registry['page__ckeditor_node_embed']['template'] = 'page--custom-ckeditor-node-embed';
  $theme_registry['page__ckeditor_node_embed']['path'] = drupal_get_path('module', 'view_subject_subpages') . "/theme";
  $theme_registry['page__ckeditor_node_embed']['render element'] = 'page';
  $theme_registry['page__ckeditor_node_embed']['base hook'] = 'page';
  $theme_registry['page__ckeditor_node_embed']['type'] = 'theme_engine';
  $theme_registry['page__ckeditor_node_embed']['theme path'] = path_to_theme();
  $theme_registry['page__ckeditor_node_embed']['preprocess functions'] = Array();
  $theme_registry['page__ckeditor_node_embed']['process functions'] = Array();

}

/**
 * Implementation of hook_views_pre_render() {
 */
function view_subject_subpages_views_pre_render(&$view) {
  if ($view->name == 'custom_ckeditor_node_embed' && $view->current_display == 'page_1') {
    node_embed_suppress_admin_menu();
  }
}