---
# Apache
---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: application-environment
  namespace: favrskovdk
spec:
  vault:
    name: akv-favrskovdk-sta
    object:
      name: application-environment
      type: secret
  output:
    secret:
      name: akvs-apache
      dataKey: APP_ENV

---
# Drupal
---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: application-environment
  namespace: favrskovdk
spec:
  vault:
    name: akv-favrskovdk-sta
    object:
      name: application-environment
      type: secret
  output:
    secret:
      name: akvs-drupal
      dataKey: APP_ENV

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: db-host
  namespace: favrskovdk
spec:
  vault:
    name: akv-favrskovdk-sta
    object:
      name: db-host
      type: secret
  output:
    secret:
      name: akvs-drupal
      dataKey: DB_HOST

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: db-schema
  namespace: favrskovdk
spec:
  vault:
    name: akv-favrskovdk-sta
    object:
      name: db-schema
      type: secret
  output:
    secret:
      name: akvs-drupal
      dataKey: DB_SCHEMA

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: db-user
  namespace: favrskovdk
spec:
  vault:
    name: akv-favrskovdk-sta
    object:
      name: db-user
      type: secret
  output:
    secret:
      name: akvs-drupal
      dataKey: DB_USER

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: db-pass
  namespace: favrskovdk
spec:
  vault:
    name: akv-favrskovdk-sta
    object:
      name: db-pass
      type: secret
  output:
    secret:
      name: akvs-drupal
      dataKey: DB_PASS

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: db-port
  namespace: favrskovdk
spec:
  vault:
    name: akv-favrskovdk-sta
    object:
      name: db-port
      type: secret
  output:
    secret:
      name: akvs-drupal
      dataKey: DB_PORT

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: trusted-host-patterns
  namespace: favrskovdk
spec:
  vault:
    name: akv-favrskovdk-sta
    object:
      name: trusted-host-patterns
      type: secret
  output:
    secret:
      name: akvs-drupal
      dataKey: TRUSTED_HOST_PATTERNS

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: external-domains
  namespace: favrskovdk
spec:
  vault:
    name: akv-favrskovdk-sta
    object:
      name: external-domains
      type: secret
  output:
    secret:
      name: akvs-drupal
      dataKey: EXTERNAL_DOMAINS

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: config-split-development
  namespace: favrskovdk
spec:
  vault:
    name: akv-favrskovdk-sta
    object:
      name: config-split-development
      type: secret
  output:
    secret:
      name: akvs-drupal
      dataKey: CONFIG_SPLIT_DEVELOPMENT

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: sitemap-domain
  namespace: favrskovdk
spec:
  vault:
    name: akv-favrskovdk-sta
    object:
      name: sitemap-domain
      type: secret
  output:
    secret:
      name: akvs-drupal
      dataKey: SITEMAP_DOMAIN

---
# New Relic
---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: newrelic-project-name
  namespace: favrskovdk
spec:
  vault:
    name: akv-favrskovdk-sta
    object:
      name: newrelic-project-name
      type: secret
  output:
    secret:
      name: akvs-newrelic
      dataKey: NEWRELIC_PROJECT_NAME

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: newrelic-license-key
  namespace: favrskovdk
spec:
  vault:
    name: akv-favrskovdk-sta
    object:
      name: newrelic-license-key
      type: secret
  output:
    secret:
      name: akvs-newrelic
      dataKey: NEWRELIC_LICENSE_KEY

