---
apiVersion: batch/v1beta1
kind: CronJob

metadata:
  name: website-cron
  namespace: favrskovdk
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            "kubernetes.io/os": linux

          volumes:
            - name: files-public-azfp
              persistentVolumeClaim:
                claimName: files-public-azfp-pvc

            - name: log-azfp
              persistentVolumeClaim:
                claimName: log-azfp-pvc

            - name: files-private-azf
              persistentVolumeClaim:
                claimName: files-private-azf-pvc

            - name: files-cache
              persistentVolumeClaim:
                claimName: files-cache-longhorn-pvc

          containers:
          - name: php
            image: acrfavrskov.azurecr.io/favrskovdk-php:1.0.0-staging.11
#            ports:
#              - containerPort: 9001
            securityContext:
              runAsUser: 0
              privileged: true
              capabilities:
                add:
                  - SYS_ADMIN # Enabled to bind mounts correctly

#            livenessProbe:
#              tcpSocket:
#                port: 9001
#              initialDelaySeconds: 10
#              periodSeconds: 3
#              timeoutSeconds: 2
#
#            readinessProbe:
#              tcpSocket:
#                port: 9001
#              initialDelaySeconds: 10
#              periodSeconds: 3
#              timeoutSeconds: 2

            resources:
              requests:
                cpu: 100m
                memory: 256Mi

            volumeMounts:
              - name: files-public-azfp
                mountPath: /app/webroot/sites/favrskov.dk/files

              - name: log-azfp
                mountPath: /mnt/logs
                subPath: website # Store under website subdir on mounted storage

              - name: files-private-azf
                mountPath: /app/private-files

              - name: files-cache
                mountPath: /mnt/cache
                subPath: cache # Store under cache subdir on mounted storage

            envFrom:
              - configMapRef:
                  name: php-env
              - secretRef:
                  name: akvs-drupal
              - secretRef:
                  name: akvs-newrelic

            command: ["/release/entrypoint.cron.sh"]

          restartPolicy: OnFailure
