---
apiVersion: cert-manager.io/v1
kind: Certificate

metadata:
  name: favrskovdk-cert
  namespace: favrskovdk
spec:
  secretName: website-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: staging.favrskov.drupal.dk
  dnsNames:
    - staging.favrskov.drupal.dk

