<?php
/**
 * @file
 * Code for the Panel Blog page feature.
 */

include_once 'panel_blog_page.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function panel_blog_page_ctools_plugin_directory($module, $plugin) {
  if (!empty($plugin)) {
    return 'plugins/' . $plugin;
  }
}

function panel_blog_page_form_comment_form_alter(&$form, &$form_state) {
  if (!isset($form['author']['_author'])) {
    $form['author']['name']['#placeholder'] = t('Name Namesen...');
  }
}