<?php
/**
 * @file
 * Drupal needs this blank file.
 */

/**
 * Implements hook_domain_menu_block_menu_name_alter().
 */
function panels_aside_menu_block_domain_menu_block_menu_name_alter(&$menu_name, $dmb, $domain) {
  if ($domain['is_default']) {
    $menu_name = 'main-menu';
  }
}

function panels_aside_menu_block_menu_breadcrumb_alter(&$active_trail, $item) {
  $domain = domain_get_domain();

  if (!$domain['is_default']) {
    $dmb = domain_menu_block_load('main_menu');
    $domain_menu = menu_load(domain_menu_block_menu_name($dmb, $domain));

    // Next part copied from menu_set_active_trail().
    $preferred_link = menu_link_get_preferred($item['path'], $domain_menu['menu_name']);
    $trail = array();
    $trail[] = array(
      'title' => t('Home'),
      'href' => '<front>',
      'link_path' => '',
      'localized_options' => array(),
      'type' => 0,
    );

    $tree = menu_tree_page_data($domain_menu['menu_name'], NULL, TRUE);
    list($key, $curr) = each($tree);

    while ($curr) {
      $link = $curr['link'];
      if ($link['in_active_trail']) {
        if (!($link['type'] & MENU_LINKS_TO_PARENT)) {
          if (strpos($link['href'], '%') !== FALSE) {
            _menu_link_translate($link, TRUE);
          }
          if ($link['access']) {
            $trail[] = $link;
          }
        }
        $tree = $curr['below'] ? $curr['below'] : array();
      }
      list($key, $curr) = each($tree);
    }

    $last = end($trail);
    if ($preferred_link && $last['href'] != $preferred_link['href'] && !drupal_is_front_page()) {
      $trail[] = $preferred_link;
    }

    $active_trail = $trail;
  }
}