<?php
/**
 * @file
 * Code for the View Matrix feature.
 */

include_once 'view_matrix.features.inc';

/**
 * Return our custom formats.
 *
 * @return
 * info about custom formats
 */
function view_matrix_date_formats_get_names() {
  static $names = array('matrix_date' => 'l d.m Y, H:i');
  return $names;
}

/**
 * Implements hook_date_formats().
 */
function view_matrix_date_formats() {
  $formats = array();
  $names = view_matrix_date_formats_get_names();

  foreach ($names as $key => $value) {
    $formats[] = array(
      'type' => $key,
      'format' => $value,
      'locales' => array(),
    );
  }

  return $formats;
}

/**
 * Implements hook_date_format_types().
 */
function view_matrix_date_format_types() {
  $types = array();
  $names = view_matrix_date_formats_get_names();

  foreach ($names as $key => $value) {
    $types[$key] = t($key);
  }

  return $types;
}

/**
 * Implements hook_flush_caches().
 */
function view_matrix_flush_caches() {
  $names = view_matrix_date_formats_get_names();
  foreach ($names as $key => $value) {
    $formats = system_get_date_formats($key);
    variable_set('date_format_' . $key, $value);

    foreach ($formats as $format) {
      if (!empty($format['dfid'])) {
        system_date_format_delete($format['dfid']);
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter.
 */
function view_matrix_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  if (!empty($form['field_taxonomy_subject_area_tid'])) {
    $form['field_taxonomy_subject_area_tid']['#options']['All'] = t('View all');
  }
}