---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: files-public-azfp-pvc
  namespace: favrskovdk
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: files-public-azfp-pv
  storageClassName: ""

---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: log-azfp-pvc
  namespace: favrskovdk
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: log-azfp-pv
  storageClassName: ""

---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: files-cache-longhorn-pvc
  namespace: favrskovdk
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "longhorn"
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: files-private-azf-pvc
  namespace: favrskovdk
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: files-private-azf-pv
  storageClassName: ""

---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: backup-azf-pvc
  namespace: favrskovdk
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
  volumeName: backup-azf-pv
  storageClassName: ""
