---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1

metadata:
  name: deployment-role
  namespace: favrskovdk
rules:
- apiGroups:
  - ""
  - apps
  - batch
  - extensions
  resources:
  - '*'
  verbs:
  - '*'

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployment-role
  namespace: favrskovdk
subjects:
  - kind: ServiceAccount
    name: deployment-user
roleRef:
  kind: Role
  name: deployment-role
  apiGroup: rbac.authorization.k8s.io
