version: "3"

services:
  php:
    volumes:
      ## For macOS users (https://wodby.com/stacks/drupal/docs/local/docker-for-mac/)
      #- ./:/var/www/html:cached # User-guided caching
      - docker-favrskov-sync:/var/www/html # Docker-sync

  apache:
    volumes:
      ## For macOS users (https://wodby.com/stacks/drupal/docs/local/docker-for-mac/)
      #- ./:/var/www/html:cached # User-guided caching
      - docker-favrskov-sync:/var/www/html # Docker-sync

volumes:
  # Docker-sync for macOS users
  docker-favrskov-sync:
    external: true
