<?php
/**
 * @file
 * Code for the Views Automatic related content feature.
 */

include_once 'views_automatic_related_content.features.inc';

/**
 * Implements hook_views_query_alter().
 */
function views_automatic_related_content_views_query_alter(&$view, &$query) {
  if($view->name == 'automatic_related_content') {
    $nid = $view->args[0];
    $node = node_load($nid);
    $query->add_where(0 ,'node.type', $node->type, '=');
    $query->add_where(1 ,'node.language', $node->language, '=');
  }
}
