<?php
/**
 * @file
 * Code for the os2web_hrmanager_job feature.
 */

include_once 'os2web_hrmanager_job.features.inc';



/**
 * Return our custom formats.
 *
 * @return
 * info about custom formats
 */
function os2web_hrmanager_job_date_formats_get_names() {
  static $names = array('short_date' => 'd-m-Y');
  return $names;
}

/**
 * Implements hook_date_formats().
 */
function os2web_hrmanager_job_date_formats() {
  $formats = array();
  $names = os2web_hrmanager_job_date_formats_get_names();

  foreach ($names as $key => $value) {
    $formats[] = array(
      'type' => $key,
      'format' => $value,
      'locales' => array(),
    );
  }

  return $formats;
}

/**
 * Implements hook_date_format_types().
 */
function os2web_hrmanager_job_date_format_types() {
  $types = array();
  $names = os2web_hrmanager_job_date_formats_get_names();

  foreach ($names as $key => $value) {
    $types[$key] = t($key);
  }

  return $types;
}

/**
 * Implements hook_flush_caches().
 */
function os2web_hrmanager_job_flush_caches() {
  $names = os2web_hrmanager_job_date_formats_get_names();
  foreach ($names as $key => $value) {
    $formats = system_get_date_formats($key);
    variable_set('date_format_' . $key, $value);

    foreach ($formats as $format) {
      if (!empty($format['dfid'])) {
        system_date_format_delete($format['dfid']);
      }
    }
  }
}

/**
 * Implements hook_feeds_after_parse().
 *
 * Body field must be full html , but we must cut html inline styles while importing.
 * This is what this function does.)))
 */
function os2web_hrmanager_job_feeds_after_parse(FeedsSource $source, FeedsParserResult $result) {
  foreach ($result->items as &$item) {
    $body = & $item['xpathparser:1'];
    $body = check_markup($body, 'job_html');
    $body = preg_replace('/&lt;\?xml[^>]+\/&gt;/i', '', $body);
    //Remove class attributes
    $body = preg_replace('/(<[^>]+) class=".*?"/i', '$1', $body);
  }
}
