.base: &base
  application: favrskov
  roles: app
  branch: develop
  slack_webhook: ""
  drupal_site: "favrskov.dk"
  docroot: 'webroot'
  repository: "git@github.com:favrskov-kommune/favrskov.dk.git"
  git_tty: true
  shared_dirs:
    - 'webroot/sites/favrskov.dk/files'
    - 'private-files'
  shared_files:
    - 'webroot/sites/favrskov.dk/settings.local.php'
    - 'webroot/sites/favrskov.dk/services.local.yml'
    - 'webroot/sites/sites.local.php'
    - '.env'
  writable_dirs:
    - 'webroot/sites/favrskov.dk/files'
  allow_anonymous_stats: false
  keep_releases: 5
  drupal_core_version: 9
  use_locale_update: true
  use_composer: true
  use_npm: true
  theme_exec_path: sites/favrskov.dk/themes/custom/favrskov/build-assets
prod:
  <<: *base
  branch: master
  deploy_path: /var/www/favrskov.dk
  hostname: '81.95.247.233'
  user: favrskov
  disable_slack: true
staging:
  <<: *base
  branch: develop
  deploy_path: /data/www/vhost/staging.favrskov.drupal.dk
  hostname: '81.95.247.111'
  user: favrskov
  disable_slack: true
  keep_releases: 2
