---
apiVersion: cert-manager.io/v1
kind: Certificate

metadata:
  name: website-cert
  namespace: favrskovdk
spec:
  secretName: website-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: favrskov.dk
  dnsNames:
    - favrskov.dk
    - www.favrskov.dk
    - prod.favrskov.drupal.dk

