---
apiVersion: cert-manager.io/v1
kind: Certificate

metadata:
  name: website-favrskovdk-cert
  namespace: favrskov
spec:
  secretName: website-favrskovdk-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: prod.favrskov.drupal.dk
  dnsNames:
    - prod.favrskov.drupal.dk
#    - favrskov.dk
#    - www.favrskov.dk

