<?php
/**
 * @file
 * taxonomy_page_subscription_category.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function taxonomy_page_subscription_category_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'taxonomy_term-page_subscription_category-field_email_body_intro_text'
  $field_instances['taxonomy_term-page_subscription_category-field_email_body_intro_text'] = array(
    'bundle' => 'page_subscription_category',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 1,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_email_body_intro_text',
    'label' => t('E-mail body intro text'),
    'required' => 0,
    'settings' => array(
      'better_formats' => array(
        'allowed_formats' => array(
          'custom_tokens_no_filters_' => 'custom_tokens_no_filters_',
          'filtered_html' => 'filtered_html',
          'full_html' => 'full_html',
          'job_html' => 'job_html',
          'mailchimp_campaign' => 'mailchimp_campaign',
          'os2web_fics_esdh' => 'os2web_fics_esdh',
          'plain_text' => 'plain_text',
          'video_html' => 'video_html',
        ),
        'allowed_formats_toggle' => 0,
        'default_order_toggle' => 0,
        'default_order_wrapper' => array(
          'formats' => array(
            'custom_tokens_no_filters_' => array(
              'weight' => 0,
            ),
            'filtered_html' => array(
              'weight' => 0,
            ),
            'full_html' => array(
              'weight' => 0,
            ),
            'job_html' => array(
              'weight' => 0,
            ),
            'mailchimp_campaign' => array(
              'weight' => 0,
            ),
            'os2web_fics_esdh' => array(
              'weight' => 0,
            ),
            'plain_text' => array(
              'weight' => 10,
            ),
            'video_html' => array(
              'weight' => 0,
            ),
          ),
        ),
      ),
      'linkit' => array(
        'enable' => 0,
        'insert_plugin' => '',
      ),
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'maxlength_js' => '',
        'maxlength_js_enforce' => 0,
        'maxlength_js_label' => 'Content limited to @limit characters, remaining: <strong>@remaining</strong>',
        'maxlength_js_truncate_html' => 0,
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 3,
    ),
  );

  // Exported field_instance: 'taxonomy_term-page_subscription_category-field_email_subject'
  $field_instances['taxonomy_term-page_subscription_category-field_email_subject'] = array(
    'bundle' => 'page_subscription_category',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_email_subject',
    'label' => t('E-mail subject'),
    'required' => 1,
    'settings' => array(
      'better_formats' => array(
        'allowed_formats' => array(
          'custom_tokens_no_filters_' => 'custom_tokens_no_filters_',
          'filtered_html' => 'filtered_html',
          'full_html' => 'full_html',
          'job_html' => 'job_html',
          'mailchimp_campaign' => 'mailchimp_campaign',
          'os2web_fics_esdh' => 'os2web_fics_esdh',
          'plain_text' => 'plain_text',
          'video_html' => 'video_html',
        ),
        'allowed_formats_toggle' => 0,
        'default_order_toggle' => 0,
        'default_order_wrapper' => array(
          'formats' => array(
            'custom_tokens_no_filters_' => array(
              'weight' => 0,
            ),
            'filtered_html' => array(
              'weight' => 0,
            ),
            'full_html' => array(
              'weight' => 0,
            ),
            'job_html' => array(
              'weight' => 0,
            ),
            'mailchimp_campaign' => array(
              'weight' => 0,
            ),
            'os2web_fics_esdh' => array(
              'weight' => 0,
            ),
            'plain_text' => array(
              'weight' => 10,
            ),
            'video_html' => array(
              'weight' => 0,
            ),
          ),
        ),
      ),
      'linkit' => array(
        'enable' => 0,
        'insert_plugin' => '',
      ),
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'maxlength_js' => 0,
        'maxlength_js_label' => 'Content limited to @limit characters, remaining: <strong>@remaining</strong>',
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 2,
    ),
  );

  // Exported field_instance: 'taxonomy_term-page_subscription_category-field_mailchimp_grouping_id'
  $field_instances['taxonomy_term-page_subscription_category-field_mailchimp_grouping_id'] = array(
    'bundle' => 'page_subscription_category',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => ' ',
        ),
        'type' => 'number_integer',
        'weight' => 3,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_mailchimp_grouping_id',
    'label' => t('mailchimp_grouping_id'),
    'required' => 0,
    'settings' => array(
      'max' => '',
      'min' => '',
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(
        'maxlength_js_label' => 'Content limited to @limit characters, remaining: <strong>@remaining</strong>',
      ),
      'type' => 'number',
      'weight' => 5,
    ),
  );

  // Exported field_instance: 'taxonomy_term-page_subscription_category-field_subscribe_page_description'
  $field_instances['taxonomy_term-page_subscription_category-field_subscribe_page_description'] = array(
    'bundle' => 'page_subscription_category',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 2,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_subscribe_page_description',
    'label' => t('Subscribe page description'),
    'required' => 0,
    'settings' => array(
      'better_formats' => array(
        'allowed_formats' => array(
          'custom_tokens_no_filters_' => 'custom_tokens_no_filters_',
          'filtered_html' => 'filtered_html',
          'full_html' => 'full_html',
          'job_html' => 'job_html',
          'mailchimp_campaign' => 'mailchimp_campaign',
          'os2web_fics_esdh' => 'os2web_fics_esdh',
          'plain_text' => 'plain_text',
          'video_html' => 'video_html',
        ),
        'allowed_formats_toggle' => 0,
        'default_order_toggle' => 0,
        'default_order_wrapper' => array(
          'formats' => array(
            'custom_tokens_no_filters_' => array(
              'weight' => 0,
            ),
            'filtered_html' => array(
              'weight' => 0,
            ),
            'full_html' => array(
              'weight' => 0,
            ),
            'job_html' => array(
              'weight' => 0,
            ),
            'mailchimp_campaign' => array(
              'weight' => 0,
            ),
            'os2web_fics_esdh' => array(
              'weight' => 0,
            ),
            'plain_text' => array(
              'weight' => 10,
            ),
            'video_html' => array(
              'weight' => 0,
            ),
          ),
        ),
      ),
      'linkit' => array(
        'enable' => 0,
        'insert_plugin' => '',
      ),
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'maxlength_js' => '',
        'maxlength_js_enforce' => 0,
        'maxlength_js_label' => 'Content limited to @limit characters, remaining: <strong>@remaining</strong>',
        'maxlength_js_truncate_html' => 0,
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 4,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('E-mail body intro text');
  t('E-mail subject');
  t('Subscribe page description');
  t('mailchimp_grouping_id');

  return $field_instances;
}
