---
apiVersion: batch/v1
kind: Job

metadata:
  name: website-database-backup
  namespace: favrskovdk
spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never

      volumes:
        - name: backup-azf
          persistentVolumeClaim:
            claimName: backup-azf-pvc

      containers:
        - name: php
          image: acrfavrskov.azurecr.io/website-php:kubernetes-1.0.12

          volumeMounts:
            - name: backup-azf
              mountPath: /mnt/backup/database
              subPath: database

          envFrom:
            - configMapRef:
                name: php-env
            - secretRef:
                name: akvs-drupal

          command: ["/release/entrypoint.database_backup.sh"]

