<?php
/**
 * @file
 * Code for the Panel Article below body mini panel feature.
 */

include_once 'panel_article_below_body_mini_panel.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 */
function panel_article_below_body_mini_panel_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  if ($form['#id'] == 'views-exposed-form-os2web-meetings-light-panel-pane-3') {
    $form['meetings_date_from']['value']['#date_format'] = 'd-m-Y';
    $form['meetings_to_date']['value']['#date_format'] = 'd-m-Y';
  }
}