<?php

/**
 * Implements hook_preprocess_HOOK().
 */
function favrskov_maps_preprocess_block__inline_block__gis_minimap(&$variables) {
  /** @var \Drupal\block_content\Entity\BlockContent $block */
  $block = $variables['elements']['content']['#block_content'];
  $map_id = $block->get('field_gis_minimap_id')->first()->getValue()['value'];
  dpm($map_id);
  if($map_id) {
    $variables['#attached']['library'][] = 'favrskov_maps/favrskov_maps.minimap';
    $variables['#attached']['drupalSettings']['favrskov_maps']['gis_minimap'][$block->id()] = $map_id;
    $variables['gis_block_id'] = $block->id();
  }

}
