<?php
/**
 * @file
 * Provides configuration and functionality for comments on article and news pages.
 * The point of this module is to provide next functionality:
 *   - Ajax comments
 *   - Replying to a comment directly
 *   - The field where the user can put his/her e-mail address.
 *   - A checkbox  where the user can check if he/she wants an e-mail notification when something new is added
 *     to the discussion on the specific node.
 */


include_once 'config_comments.features.inc';


/**
 * Implements hook_ctools_plugin_directory().
 */
function config_comments_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_form_comment_form_alter().
 *
 * Removes homepage textfield for anonymous users on comment posting and attaching custom js.
 */
function config_comments_form_comment_form_alter(&$form) {
  $form['author']['homepage']['#access'] = FALSE;
  $form['#attached']['js'][] = array(drupal_get_path('module', 'config_comments') . '/config_comments.js');
}

/**
 * Implements hook_preprocess_comment().
 *
 * Changes format of date displaying in comment.
 */
function config_comments_preprocess_comment(&$variables) {
  $variables['created'] = format_date($variables['elements']['#comment']->created, 'custom', 'd. F Y - h:i');
  $variables['submitted'] = t('Submitted by !username on !datetime', array(
    '!username' => $variables['author'],
    '!datetime' => $variables['created']
  ));
}

function config_comments_panels_pane_content_alter(&$content, $pane, $args, $context) {
  if ($pane->type == 'node_comments') {
    if ($context['argument_entity_id:node_1']->data->comment_count == 0) {
      unset($content->title);
    }

  }
}